// src/components/DoctorLetter.jsx — printable medication reconciliation letter
import { DownloadIcon } from './Icons.jsx'

export default function DoctorLetter({ letterText, patient, analyzedAt }) {
  const handlePrint = () => window.print()
  const date = analyzedAt ? new Date(analyzedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : ''

  if (!letterText) return null

  return (
    <>
      {/* Print-only styles */}
      <style>{`
        @media print {
          body > *:not(#doctor-letter-root) { display: none !important; }
          #doctor-letter-root { display: block !important; position: fixed; top: 0; left: 0; width: 100%; z-index: 9999; background: #fff; padding: 2rem; }
          .no-print { display: none !important; }
        }
      `}</style>

      <div
        id="doctor-letter-root"
        className="rounded-2xl overflow-hidden"
        style={{ border: '1px solid #E2E8F0', background: '#fff', boxShadow: '0 1px 3px rgba(15,23,42,0.06)' }}
      >
        {/* Letter header */}
        <div
          className="px-6 py-4 flex items-center justify-between"
          style={{ background: 'linear-gradient(135deg,#1D56DB,#2563EB)' }}
        >
          <div>
            <div className="font-black text-base" style={{ color: '#fff' }}>Medication Reconciliation Letter</div>
            <div className="text-sm mt-0.5" style={{ color: 'rgba(255,255,255,0.75)' }}>Generated by Agastya AI · {date}</div>
          </div>
          <button
            onClick={handlePrint}
            className="no-print flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold transition-all"
            style={{ background: 'rgba(255,255,255,0.15)', color: '#fff', border: '1px solid rgba(255,255,255,0.25)' }}
          >
            <DownloadIcon className="w-4 h-4" />
            Print
          </button>
        </div>

        {/* Letter body */}
        <div className="px-6 py-5">
          <div className="mb-4 p-3 rounded-xl text-sm font-medium"
            style={{ background: 'rgba(37,99,235,0.06)', color: '#2563EB', border: '1px solid rgba(37,99,235,0.15)' }}>
            Print this letter and bring it to every doctor visit so your doctors know all your current medications.
          </div>
          <pre
            className="whitespace-pre-wrap text-sm leading-relaxed"
            style={{ color: '#334155', fontFamily: 'inherit' }}
          >
            {letterText}
          </pre>
        </div>
      </div>
    </>
  )
}
